In [9]:
import numpy as np
import pandas as pd

In [2]:
import torch
print(torch.__version__)

1.13.1+cpu


In [5]:
# Scalar
scalar  = torch.tensor(7)
scalar
print(scalar.ndim)
print(scalar.item())

0


In [10]:
# Vector
vector = torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [15]:
# Matrix
MATRIX = torch.tensor([[7, 8, 4], 
                       [9, 10, 7]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[ 7,  8,  4],
        [ 9, 10,  7]])
2
torch.Size([2, 3])


In [18]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                        [[3,2,1],
                        [9,6,3],
                        [5,4,2]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape) # Dimension go outer to inner

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[3, 2, 1],
         [9, 6, 3],
         [5, 4, 2]]])
3
torch.Size([2, 3, 3])


In [27]:
dim_4 = torch.tensor(
[
    [
        [
            [1,1,1,1],
            [2,3,1,4],
            [2,3,1,4]
        ],
        [
            [1,7,7,7],
            [2,3,1,4],
            [2,3,1,4]
        ]
    ]
])
print(dim_4)
print(dim_4.ndim)
print(dim_4.shape)

tensor([[[[1, 1, 1, 1],
          [2, 3, 1, 4],
          [2, 3, 1, 4]],

         [[1, 7, 7, 7],
          [2, 3, 1, 4],
          [2, 3, 1, 4]]]])
4
torch.Size([1, 2, 3, 4])


In [7]:
# Create tensor with random numbers
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.8827, 0.6494, 0.0691, 0.0525],
         [0.0031, 0.0497, 0.6188, 0.4173],
         [0.0630, 0.1696, 0.0928, 0.2360]]),
 torch.float32)

In [20]:
# Image for size 5x5 with RGB 3 | 2 is number of images
random_img_tensor = torch.rand(size=(3,5,5))
random_img_tensor

tensor([[[0.3907, 0.6507, 0.9551, 0.9137, 0.2400],
         [0.6726, 0.4242, 0.0907, 0.1544, 0.8515],
         [0.8927, 0.1642, 0.1426, 0.3215, 0.5109],
         [0.6970, 0.6042, 0.5303, 0.6880, 0.2838],
         [0.4736, 0.2711, 0.6869, 0.0851, 0.7358]],

        [[0.6438, 0.7630, 0.5302, 0.1211, 0.1047],
         [0.9176, 0.7584, 0.5811, 0.4055, 0.2945],
         [0.2268, 0.8173, 0.9355, 0.0497, 0.8765],
         [0.9378, 0.8684, 0.5580, 0.2927, 0.1578],
         [0.2489, 0.2706, 0.8387, 0.4973, 0.7459]],

        [[0.6164, 0.7793, 0.8323, 0.3430, 0.0920],
         [0.4740, 0.2230, 0.1584, 0.8059, 0.6487],
         [0.0402, 0.3201, 0.9487, 0.6588, 0.5385],
         [0.3077, 0.7657, 0.9873, 0.8756, 0.7414],
         [0.6994, 0.0917, 0.2585, 0.4199, 0.5420]]])

In [22]:
# Zeroes and ones
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [25]:
# Arrange function
nums = torch.arange(0,10,2)
# ones_like will take the shape of nums vector
nums , torch.ones_like(nums)

(tensor([0, 2, 4, 6, 8]), tensor([1, 1, 1, 1, 1]))

In [40]:
# We have torch.float/16/32/64/half series for precision
torch.half, torch.double, torch.float

(torch.float16, torch.float64, torch.float32)

In [46]:
# Default datatype for tensors is float32
# One of tensors is torch.float32 and the other is torch.float16 (PyTorch often likes tensors to be the same format).
# Or one of your tensors is on the CPU and the other is on the GPU (PyTorch likes calculations between tensors to be on the same device).

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device, float_32_tensor

(torch.Size([3]),
 torch.float16,
 device(type='cpu'),
 tensor([3., 6., 9.], dtype=torch.float16))

In [47]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU
# Note: When you run into issues in PyTorch, it's very often one to do with one of the three attributes above. 
# So when the error messages show up, sing yourself a little song called "what, what, where":

tensor([[0.4237, 0.1146, 0.4198, 0.4931],
        [0.6763, 0.1550, 0.7401, 0.2675],
        [0.3947, 0.4314, 0.7561, 0.1080]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Tensor operation +,-,*,/

In [58]:
tensor = torch.tensor([1,2,3,5])
tensor + 7, tensor*10

(tensor([ 8,  9, 10, 12]), tensor([10, 20, 30, 50]))

In [59]:
tensor = tensor * 10
tensor - 5, tensor

(tensor([ 5, 15, 25, 45]), tensor([10, 20, 30, 50]))

In [60]:
torch.multiply(tensor,10) # Multiply, add functions 

tensor([100, 200, 300, 500])

In [61]:
tensor

tensor([10, 20, 30, 50])

In [62]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([10, 20, 30, 50]) * tensor([10, 20, 30, 50])
Equals: tensor([ 100,  400,  900, 2500])


In [5]:
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [64]:
tensor*tensor, torch.matmul(tensor,tensor)

(tensor([1, 4, 9]), tensor(14))

In [65]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [66]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 29.6 ms


tensor(14)

In [7]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [13]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10, 8],
                         [8, 11, 9]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B), tensor_A.shape, tensor_B.shape

(tensor([[ 23.,  32.,  26.],
         [ 53.,  74.,  60.],
         [ 83., 116.,  94.]]),
 torch.Size([3, 2]),
 torch.Size([2, 3]))

In [14]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [15]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [16]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

### Torch for feed forward nn

In [37]:
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, out_features=6)
# This will create W and b for y= x*W + b
print(linear.weight.shape, linear.bias.shape)
linear.weight, linear.bias, linear.parameters

torch.Size([6, 2]) torch.Size([6])


(Parameter containing:
 tensor([[ 0.5406,  0.5869],
         [-0.1657,  0.6496],
         [-0.1549,  0.1427],
         [-0.3443,  0.4153],
         [ 0.6233, -0.5188],
         [ 0.6146,  0.1323]], requires_grad=True),
 Parameter containing:
 tensor([ 0.5224,  0.0958,  0.3410, -0.0998,  0.5451,  0.1045],
        requires_grad=True),
 <bound method Module.parameters of Linear(in_features=2, out_features=6, bias=True)>)

In [33]:
x = tensor_A
x, x.shape

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 torch.Size([3, 2]))

In [34]:
output = linear(x)
output, output.shape # y = x*W + b
# Here (3,2) X (2,6) + (1,6) -> (3,6)

(tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
         [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
         [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
        grad_fn=<AddmmBackward0>),
 torch.Size([3, 6]))

In [58]:
x = torch.tensor([[1., -1.], [1., 1.]], requires_grad=True)
out = x.pow(2).sum() + 3
back = out.backward()
x, out, back, x.grad

(tensor([[ 1., -1.],
         [ 1.,  1.]], requires_grad=True),
 tensor(7., grad_fn=<AddBackward0>),
 None,
 tensor([[ 2., -2.],
         [ 2.,  2.]]))

### Torch for aggregation

In [38]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")
# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450
Index where max value occurs: 2
Index where min value occurs: 0


In [43]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [45]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [46]:
# Convert float32 to float16
tensor_float16 = tensor.type(torch.float16)
tensor_float16.dtype

torch.float16

In [51]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

### Reshaping, stacking, squeezing, unsqueezing

In [70]:
# Returns a view of original tensor in different shape
tensor_int8.view(1,9)

tensor([[10, 20, 30, 40, 50, 60, 70, 80, 90]], dtype=torch.int8)

In [87]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
torch.stack((tensor_A,tensor_B),dim=0), torch.stack((tensor_A,tensor_B),dim=0).shape

(tensor([[[ 1.,  2.],
          [ 3.,  4.],
          [ 5.,  6.]],
 
         [[ 7., 10.],
          [ 8., 11.],
          [ 9., 12.]]]),
 torch.Size([2, 3, 2]))

In [88]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [89]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [90]:
# Change view (keeps same data as original but changes view)
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [91]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [92]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked # Row stack for 2d, so dim=0

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [95]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked # Column stack for 2d, so dim=1

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [96]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [97]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0) # Row unsqueeze
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [100]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1) # Col unsqueeze
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.]])
New shape: torch.Size([7, 1])


In [102]:
# Create tensor with specific shape
x_original = torch.rand(size=(3, 3, 2))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")
x_original, x_permuted

Previous shape: torch.Size([3, 3, 2])
New shape: torch.Size([2, 3, 3])


(tensor([[[0.8399, 0.1374],
          [0.2331, 0.9578],
          [0.3313, 0.3227]],
 
         [[0.0162, 0.2137],
          [0.6249, 0.4340],
          [0.1371, 0.5117]],
 
         [[0.1585, 0.0758],
          [0.2247, 0.0624],
          [0.1816, 0.9998]]]),
 tensor([[[0.8399, 0.2331, 0.3313],
          [0.0162, 0.6249, 0.1371],
          [0.1585, 0.2247, 0.1816]],
 
         [[0.1374, 0.9578, 0.3227],
          [0.2137, 0.4340, 0.5117],
          [0.0758, 0.0624, 0.9998]]]))

### Indexing and selection in tensors

In [103]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [104]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [115]:
x[:1,:,:], x[:,:,1]

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([[2, 5, 8]]))

### Pytorch and numpy
* `torch.from_numpy(ndarray)` - NumPy array -> PyTorch tensor.
* `torch.Tensor.numpy()` - PyTorch tensor -> NumPy array.

In [1]:
import torch
import numpy as np
torch.__version__ , np.__version__

('1.13.1+cpu', '1.21.5')

In [3]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [7]:
tensor = torch.from_numpy(array).type(torch.float32)
array, array.dtype, tensor, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [8]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [9]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [12]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [11]:
# Check for GPU
import torch
torch.cuda.is_available()

False

In [13]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [14]:
# Count number of devices
torch.cuda.device_count()

0

In [15]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

In [16]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)